### ISSUE TITLE
Incompatibility with recent sklearn versions?

### ISSUE THREAD

**Issue by romanovzky** [jakevdp/wpca#10]
Hi there, with my current setup with `sklearn==0.24.2` if I have `X` and `weights` with

```python
X.shape = ( n_samples, n_features)
weights.shape = ( n_samples, )
```

I get the error
```
ValueError: Expected 2D array, got 1D array instead:
array=...
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```
If I do the reshape of `weights` to `(n_samples, 1)` I then get `ValueError: Shape of `X` and `weights` should match`.

So there's something broken with current versions. Cheers

**Comment by jakevdp** [comment]
The last commit in this repository was over 5 years ago, and scikit-learn has evolved a lot since then. It wouldn’t surprise me if the packages are no longer compatible.

This repo is permissively licensed; feel free to fork it if you wish to develop it further.
